-- CreateEnum
CREATE TYPE "WorkOrderType" AS ENUM ('INSTALLATION', 'MAINTENANCE', 'REPAIR', 'TROUBLESHOOTING', 'INSPECTION', 'OTHER');

-- AlterTable
ALTER TABLE "WorkOrder" ADD COLUMN     "type" "WorkOrderType" NOT NULL DEFAULT 'INSTALLATION';
