import { PlanType, PlanFeatures } from "./types";

export const PLAN_CONFIGS: Record<PlanType, PlanFeatures> = {
  [PlanType.SOLO]: {
    name: "Solo",
    description: "Perfect for individual operators",
    price: 29,
    maxUsers: 1,
    features: [
      "1 User Account",
      "Unlimited Work Orders",
      "Basic Customer Management",
      "Invoicing & Payments",
      "Standard Reports",
      "Email Support",
    ],
    isPopular: false,
  },
  [PlanType.TEAM]: {
    name: "Team",
    description: "Designed for small to medium teams",
    price: 59,
    maxUsers: 10,
    features: [
      "Up to 10 User Accounts",
      "Unlimited Work Orders",
      "Advanced Customer Management",
      "Team Scheduling & Dispatch",
      "Advanced Reports & Analytics",
      "Priority Email Support",
      "Role-based Access Control",
    ],
    isPopular: true,
  },
  [PlanType.BUSINESS]: {
    name: "Business",
    description: "Comprehensive solution for growing businesses",
    price: 99,
    maxUsers: 50,
    features: [
      "Up to 50 User Accounts",
      "All Team Plan Features",
      "Customizable Workflows",
      "API Access",
      "Dedicated Account Manager",
      "Phone & Chat Support",
      "Advanced Integrations",
    ],
    isPopular: false,
  },
  [PlanType.ENTERPRISE]: {
    name: "Enterprise",
    description: "Tailored for large-scale operations",
    price: 0,
    maxUsers: 0,
    features: [
      "Unlimited Users",
      "All Business Plan Features",
      "Custom Integrations",
      "On-premise Deployment Options",
      "SLA & Uptime Guarantees",
      "24/7 Premium Support",
    ],
    isPopular: false,
  },
}; 